### PR TITLE
System Memory Allocator

### PR DESCRIPTION
**Pull request by DethRaid**
Adds `system_memory_allocator`. This is an allocator for system memory, as the name implies. It takes in a pointer to the memory region it can allocate from, the size of that memory region, and an allocation strategy instance. The allocation strategy can do whatever you want. In this way we can service all system memory allocation needs with a single class, and we can share allocation strategies between system memory and video memory

Due to the fact that my allocation strategies have a different interface than `bvestl::polyalloc::Allocator`, `SystemMemoryAllocator` has to store some data internally. This is currently done with an `eastl::unordered_map`. While I would like a way to control that map's allocation, it only gets used when allocating or deallocating, and that happens during loading or unloading, and I expect those to be relatively common situations. I don't think it's critical to have that functionality.

I've added VCPKG files to the root of the repo. However, they refer to a tag that doesn't yet exist. I'll have to update them once this is all merged in

### CODE REVIEW

**Comment by DethRaid** [comment]
I'm no longer using BVESTL so I'm closing this pr

**Comment by cwfitzgerald** [comment]
Why have you betayed me like this

**Comment by DethRaid** [comment]
You betrayed me first, Mr Make BVE In Unity

**Comment by cwfitzgerald** [comment]
Your face is in unity

**Pull request closed without merging**
